import { useState } from "react";
import { desktopApi } from "../lib/desktopApi";
import "./common.css";

interface Props { onRestored: () => void; }
export default function BackupPage({onRestored}:Props){const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 async function backup(){setBusy(true);setError("");setMessage("");try{const path=await desktopApi.createBackup();setMessage(path?`Backup saved to ${path}`:"Backup was cancelled.");}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 async function restore(){if(!window.confirm("Restore stores, settings, and history from a backup? Existing records with the same ID will be updated. Access tokens are not included."))return;setBusy(true);setError("");setMessage("");try{const result=await desktopApi.restoreBackup();if(result.cancelled){setMessage("Restore was cancelled.");}else{setMessage(`Restore completed: ${result.stores} stores, ${result.settings} settings, ${result.history} history records. Re-enter access tokens if needed.`);onRestored();}}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 return <div className="page-stack"><section className="page-hero"><div><span className="eyebrow">LOCAL BACKUP</span><h2>Back up stores, settings, and activity</h2><p>Create one portable ZIP file for local application metadata. Shopify access tokens are intentionally excluded.</p></div><aside><small>BACKUP FORMAT</small><strong>ZIP + JSON</strong></aside></section>{message&&<div className="notice notice-success">✓ {message}</div>}{error&&<div className="notice notice-error">! {error}</div>}<section className="grid-two"><article className="page-card"><header><div><h3>Create backup</h3><p>Includes store metadata, per-store settings, and local history.</p></div></header><div className="page-card-body"><div className="notice">Access tokens remain in Windows Credential Manager or macOS Keychain and are not copied into the archive.</div><div className="form-actions"><button className="button-primary" disabled={busy} onClick={()=>void backup()}>{busy?"Working...":"Save Backup ZIP"}</button></div></div></article><article className="page-card"><header><div><h3>Restore backup</h3><p>Merge a supported backup into this installation.</p></div></header><div className="page-card-body"><div className="notice notice-warning">After restoring on another computer, open Stores and enter each access token again.</div><div className="form-actions"><button className="button-secondary" disabled={busy} onClick={()=>void restore()}>{busy?"Working...":"Choose Backup ZIP"}</button></div></div></article></section></div>}
