import { useState } from "react";
import { desktopApi, isTauriRuntime, type StoreRecord } from "../lib/desktopApi";
import "./common.css";
import ThemeDownloadCard from "./ThemeDownloadCard";

interface Props { onRestored: () => void; activeStore: StoreRecord | null; onHistoryChanged: () => void; }
export default function BackupPage({onRestored,activeStore,onHistoryChanged}:Props){const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
 async function backup(){setBusy(true);setError("");setMessage("");try{const path=await desktopApi.createBackup();setMessage(path?`Backup saved to ${path}`:"Backup was cancelled.");}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 async function restore(){if(!window.confirm("Restore stores, settings, and history from a backup? Existing records with the same ID will be updated. Access tokens are not included."))return;setBusy(true);setError("");setMessage("");try{const result=await desktopApi.restoreBackup();if(result.cancelled){setMessage("Restore was cancelled.");}else{setMessage(`Restore completed: ${result.stores} stores, ${result.settings} settings, ${result.history} history records. Re-enter access tokens if needed.`);onRestored();}}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 return <div className="page-stack"><section className="page-hero"><div><span className="eyebrow">{isTauriRuntime()?"LOCAL BACKUP":"PORTABLE BACKUP"}</span><h2>Download a theme or back up your workspace</h2><p>Download your selected Shopify theme as a ZIP, or save application settings and activity as a separate workspace backup.</p></div><aside><small>BACKUP FORMAT</small><strong>ZIP + JSON</strong></aside></section><ThemeDownloadCard key={`${activeStore?.id || "none"}:${activeStore?.updatedAt || ""}`} store={activeStore} onHistoryChanged={onHistoryChanged}/>{message&&<div className="notice notice-success">✓ {message}</div>}{error&&<div className="notice notice-error">! {error}</div>}<section className="grid-two"><article className="page-card"><header><div><h3>Create backup</h3><p>Includes store metadata, per-store settings, and local history.</p></div></header><div className="page-card-body"><div className="notice">{isTauriRuntime()?"Access tokens remain in Windows Credential Manager or macOS Keychain and are not copied into the archive.":"Encrypted access tokens remain in PostgreSQL and are not copied into the archive."}</div><div className="form-actions"><button className="button-primary" disabled={busy} onClick={()=>void backup()}>{busy?"Working...":"Save Backup ZIP"}</button></div></div></article><article className="page-card"><header><div><h3>Restore backup</h3><p>Merge a supported backup into this installation.</p></div></header><div className="page-card-body"><div className="notice notice-warning">After restoring into another workspace, open Stores and enter each access token again.</div><div className="form-actions"><button className="button-secondary" disabled={busy} onClick={()=>void restore()}>{busy?"Working...":"Choose Backup ZIP"}</button></div></div></article></section></div>}
