import { useState } from "react";
import { createAdminClient } from "../lib/shopifyClient";
import { desktopApi, type StoreRecord } from "../lib/desktopApi";
import type { AppSettings } from "../lib/appSettings";
import { startCollectionExport, getCollectionExportStatus, createCollectionExportFile, type CollectionExportFormat, type CollectionExportOperation, type SourceFilter } from "../lib/collection-export/collectionExport";
import { saveResponse } from "../lib/fileSave";
import "./common.css";

interface Props { activeStore: StoreRecord | null; settings: AppSettings; onHistoryChanged: () => void; }
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

export default function CollectionExportPage({activeStore,settings,onHistoryChanged}:Props){
 const [query,setQuery]=useState(""); const [sourceFilter,setSourceFilter]=useState<SourceFilter>("all"); const [format,setFormat]=useState<CollectionExportFormat>(settings.export.defaultFormat); const [includeProducts,setIncludeProducts]=useState(true); const [includeMetafields,setIncludeMetafields]=useState(true); const [operation,setOperation]=useState<CollectionExportOperation|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 async function run(){if(!activeStore){setError("Select an active store first.");return;}setBusy(true);setError("");setMessage("");
  let history=await desktopApi.saveHistory({storeId:activeStore.id,kind:"collection-export",name:`collections-export-${new Date().toISOString().slice(0,10)}`,status:"RUNNING",total:0,processed:0,createdCount:0,updatedCount:0,skippedCount:0,failedCount:0,detailsJson:JSON.stringify({query,sourceFilter,format,includeProducts,includeMetafields})});
  try{const admin=createAdminClient(activeStore.id, "2026-07");let op=await startCollectionExport(admin,{query,includeProducts,includeMetafields});setOperation(op);while(!["COMPLETED","FAILED","CANCELED","EXPIRED"].includes(op.status)){await sleep(1800);op=await getCollectionExportStatus(admin,op.id);setOperation(op);}if(op.status!=="COMPLETED")throw new Error(`Export ended with ${op.status}${op.errorCode?`: ${op.errorCode}`:""}.`);
   const delimiter=settings.export.csvDelimiter==="semicolon"?";":settings.export.csvDelimiter==="tab"?"\t":",";
   const response=await createCollectionExportFile(admin,op.id,format,activeStore.domain,sourceFilter,{delimiter,includeBom:settings.export.csvEncoding==="utf8-bom"}); const path=await saveResponse(response,`collections-export.${format}`); await desktopApi.saveHistory({id:history.id,storeId:activeStore.id,kind:"collection-export",name:history.name,status:"COMPLETED",total:Number(op.rootObjectCount||0),processed:Number(op.rootObjectCount||0),createdCount:0,updatedCount:0,skippedCount:0,failedCount:0,filePath:path||"",detailsJson:JSON.stringify({query,sourceFilter,format,operation:op})});setMessage(path?`Export saved to ${path}`:"Export completed. File saving was cancelled.");onHistoryChanged();
  }catch(reason){await desktopApi.saveHistory({id:history.id,storeId:activeStore.id,kind:"collection-export",name:history.name,status:"FAILED",total:Number(operation?.rootObjectCount||0),processed:0,createdCount:0,updatedCount:0,skippedCount:0,failedCount:1,detailsJson:JSON.stringify({error:String(reason)})});setError(String(reason));onHistoryChanged();}finally{setBusy(false);}}
 return <div className="page-stack">
  <section className="page-hero"><div><span className="eyebrow">HYBRID COLLECTION EXPORT</span><h2>Preserve Shopify collection sources</h2><p>Conditions, manual selections, exclusions, product or variant targets, sub-collections, images, SEO, and metafields are exported.</p></div><aside><small>ACTIVE STORE</small><strong>{activeStore?.name||"No store"}</strong></aside></section>
  {message&&<div className="notice notice-success">✓ {message}</div>}{error&&<div className="notice notice-error">! {error}</div>}
  <section className="page-card"><header><div><h3>Export options</h3><p>The source filter is applied after Shopify prepares the collection data.</p></div></header><div className="page-card-body"><div className="form-grid">
   <div className="field"><label>Source filter</label><select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value as SourceFilter)}><option value="all">All collections</option><option value="conditions">Contains conditions</option><option value="manual-selections">Contains manual selections</option><option value="exclusions">Contains exclusions</option><option value="subcollections">Contains sub-collections</option><option value="app-sources">App-owned sources</option><option value="hybrid">Hybrid collections</option><option value="products">Product targets</option><option value="variants">Variant targets</option></select></div>
   <div className="field"><label>File format</label><select value={format} onChange={e=>setFormat(e.target.value as CollectionExportFormat)}><option value="csv">CSV</option><option value="xlsx">XLSX</option><option value="json">JSON</option></select></div>
   <div className="field field-wide"><label>Shopify search query</label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='title:"Baubedarf" or handle:adidas' /></div>
   <label className="checkbox-row"><input type="checkbox" checked={includeProducts} onChange={e=>setIncludeProducts(e.target.checked)} /><span><strong>Include final product memberships</strong></span></label>
   <label className="checkbox-row"><input type="checkbox" checked={includeMetafields} onChange={e=>setIncludeMetafields(e.target.checked)} /><span><strong>Include collection metafields</strong></span></label>
  </div><div className="form-actions"><button className="button-primary" disabled={busy||!activeStore} onClick={()=>void run()}>{busy?"Preparing export...":"Start Collection Export"}</button></div></div></section>
  {operation&&<section className="page-card"><header><div><h3>Bulk operation</h3><p>{operation.id}</p></div><span className={`status-pill ${operation.status==="COMPLETED"?"status-success":operation.status==="FAILED"?"status-error":"status-running"}`}>{operation.status}</span></header><div className="page-card-body"><div className="stats-row"><div className="mini-stat"><span>Collections</span><strong>{operation.rootObjectCount}</strong></div><div className="mini-stat"><span>Total objects</span><strong>{operation.objectCount}</strong></div><div className="mini-stat"><span>File size</span><strong>{operation.fileSize||"—"}</strong></div><div className="mini-stat"><span>Error</span><strong>{operation.errorCode||"0"}</strong></div></div></div></section>}
 </div>;
}
