import { ChangeEvent, useMemo, useState } from "react";
import { parseCollectionImportFile, missingRequiredColumns, validateCollectionRows, type ParsedCollectionFile, type CollectionImportResult } from "../lib/collection-import/collectionImport.shared";
import { importCollectionRow } from "../lib/collection-import/collectionImport";
import { createAdminClient } from "../lib/shopifyClient";
import { desktopApi, type StoreRecord } from "../lib/desktopApi";
import type { AppSettings } from "../lib/appSettings";
import "./common.css";

interface Props { activeStore: StoreRecord | null; settings: AppSettings; onHistoryChanged: () => void; }
interface RowResult extends CollectionImportResult { rowIndex: number; title: string; handle: string; }

export default function CollectionImportPage({activeStore,settings,onHistoryChanged}:Props){
 const [file,setFile]=useState<ParsedCollectionFile|null>(null); const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [testPassed,setTestPassed]=useState(false); const [progress,setProgress]=useState(0); const [results,setResults]=useState<RowResult[]>([]);
 const validations=useMemo(()=>file?validateCollectionRows(file.rows):[],[file]); const readyRows=useMemo(()=>file?file.rows.filter((_,i)=>validations[i]?.status!=="error"):[],[file,validations]); const errors=validations.filter(v=>v.status==="error").length; const warnings=validations.filter(v=>v.status==="warning").length;
 async function choose(event:ChangeEvent<HTMLInputElement>){const selected=event.target.files?.[0];if(!selected)return;setError("");setMessage("");setResults([]);setTestPassed(false);try{const parsed=await parseCollectionImportFile(selected);const missing=missingRequiredColumns(parsed.headers);if(missing.length)throw new Error(`Missing required columns: ${missing.join(", ")}`);setFile(parsed);}catch(reason){setFile(null);setError(String(reason));}finally{event.target.value="";}}
 async function test(){if(!activeStore||!file||readyRows.length===0){setError("Connect a store and load at least one valid collection.");return;}setBusy(true);setError("");setMessage("");try{const row=readyRows[0];const result=await importCollectionRow(createAdminClient(activeStore.id, "2026-07"),activeStore.domain,row,settings.collection,true);if(!result.ok)throw new Error(result.error||"Collection test failed.");setTestPassed(true);setMessage(`Test collection created: ${result.collectionTitle}. Delete the [TEST] collection from Shopify after verification.`);}catch(reason){setTestPassed(false);setError(String(reason));}finally{setBusy(false);}}
 async function run(){if(!activeStore||!file){setError("Connect a store and select a file.");return;}if(errors>0){setError("Fix invalid collection rows before importing.");return;}if(settings.collection.requireTest&&!testPassed){setError("Run the safe test import before the full import.");return;}setBusy(true);setError("");setMessage("");setResults([]);setProgress(0);
  let history=await desktopApi.saveHistory({storeId:activeStore.id,kind:"collection-import",name:file.filename,status:"RUNNING",total:file.rows.length,processed:0,createdCount:0,updatedCount:0,skippedCount:0,failedCount:0,detailsJson:"[]"});const out:RowResult[]=[];
  try{for(let index=0;index<file.rows.length;index++){const row=file.rows[index];const result=await importCollectionRow(createAdminClient(activeStore.id, "2026-07"),activeStore.domain,row,settings.collection,false);out.push({...result,rowIndex:index+2,title:row.Title,handle:row.Handle});setResults([...out]);setProgress(Math.round(((index+1)/file.rows.length)*100));const created=out.filter(x=>x.action==="created").length;const updated=out.filter(x=>x.action==="updated").length;const skipped=out.filter(x=>x.action==="skipped").length;const failed=out.filter(x=>!x.ok).length;history=await desktopApi.saveHistory({id:history.id,storeId:activeStore.id,kind:"collection-import",name:file.filename,status:"RUNNING",total:file.rows.length,processed:index+1,createdCount:created,updatedCount:updated,skippedCount:skipped,failedCount:failed,detailsJson:JSON.stringify(out)});if(!result.ok&&!settings.collection.continueOnError)break;}
   const failed=out.filter(x=>!x.ok).length;await desktopApi.saveHistory({id:history.id,storeId:activeStore.id,kind:"collection-import",name:file.filename,status:failed>0&&!settings.collection.continueOnError?"FAILED":"COMPLETED",total:file.rows.length,processed:out.length,createdCount:out.filter(x=>x.action==="created").length,updatedCount:out.filter(x=>x.action==="updated").length,skippedCount:out.filter(x=>x.action==="skipped").length,failedCount:failed,detailsJson:JSON.stringify(out)});setMessage(`Collection import finished: ${out.length} processed, ${failed} failed.`);onHistoryChanged();
  }catch(reason){await desktopApi.saveHistory({id:history.id,storeId:activeStore.id,kind:"collection-import",name:file.filename,status:"FAILED",total:file.rows.length,processed:out.length,createdCount:out.filter(x=>x.action==="created").length,updatedCount:out.filter(x=>x.action==="updated").length,skippedCount:out.filter(x=>x.action==="skipped").length,failedCount:Math.max(1,out.filter(x=>!x.ok).length),detailsJson:JSON.stringify({results:out,error:String(reason)})});setError(String(reason));onHistoryChanged();}finally{setBusy(false);}}
 return <div className="page-stack">
  <section className="page-hero"><div><span className="eyebrow">HYBRID COLLECTION IMPORT</span><h2>Import Shopify source-based collections</h2><p>Conditions, manual selections, exclusions, sub-collections, images, SEO, and metafields are rebuilt for the active store.</p></div><aside><small>ACTIVE STORE</small><strong>{activeStore?.name||"No store"}</strong></aside></section>
  {message&&<div className="notice notice-success">✓ {message}</div>}{error&&<div className="notice notice-error">! {error}</div>}
  <section className="page-card"><header><div><h3>Select a collection file</h3><p>CSV, XLSX, XLS, and JSON are supported.</p></div></header><div className="page-card-body"><div className="field"><input type="file" accept=".csv,.xlsx,.xls,.json" onChange={e=>void choose(e)} /></div></div></section>
  {file&&<><section className="stats-row"><div className="mini-stat"><span>Rows</span><strong>{file.rows.length}</strong></div><div className="mini-stat"><span>Ready</span><strong>{validations.filter(v=>v.status==="ready").length}</strong></div><div className="mini-stat"><span>Warnings</span><strong>{warnings}</strong></div><div className="mini-stat"><span>Errors</span><strong>{errors}</strong></div></section>
   <section className="page-card"><header><div><h3>Validation preview</h3><p>{file.filename} · {file.sheetName}</p></div><div className="toolbar-group"><button className="button-secondary" disabled={busy||!activeStore||readyRows.length===0} onClick={()=>void test()}>{busy?"Working...":testPassed?"Run Test Again":"Safe Test Import"}</button><button className="button-primary" disabled={busy||!activeStore||errors>0||(settings.collection.requireTest&&!testPassed)} onClick={()=>void run()}>{busy?`Importing ${progress}%`:"Start Full Import"}</button></div></header>{busy&&<div className="page-card-body"><div className="progress-bar"><span style={{width:`${progress}%`}} /></div></div>}<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Row</th><th>Collection</th><th>Sources</th><th>Conditions</th><th>Selections</th><th>Exclusions</th><th>Status</th><th>Issues</th></tr></thead><tbody>{validations.map(item=><tr key={item.rowIndex}><td>{item.rowIndex}</td><td><strong>{item.title}</strong><br/><small>{item.handle}</small></td><td>{item.sourceCount}</td><td>{item.conditionCount}</td><td>{item.manualSelectionCount}</td><td>{item.exclusionCount}</td><td><span className={`status-pill ${item.status==="ready"?"status-success":item.status==="error"?"status-error":""}`}>{item.status}</span></td><td>{item.issues.map(x=>x.message).join(" · ")||"No issues"}</td></tr>)}</tbody></table></div></section>
   {results.length>0&&<section className="page-card"><header><div><h3>Import results</h3></div></header><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Row</th><th>Collection</th><th>Action</th><th>Result</th><th>Warnings / Error</th></tr></thead><tbody>{results.map(item=><tr key={`${item.rowIndex}-${item.handle}`}><td>{item.rowIndex}</td><td>{item.title}<br/><small>{item.handle}</small></td><td>{item.action||"—"}</td><td><span className={`status-pill ${item.ok?"status-success":"status-error"}`}>{item.ok?"Success":"Failed"}</span></td><td>{[...(item.warnings||[]),item.error||""].filter(Boolean).join(" · ")||"No issues"}</td></tr>)}</tbody></table></div></section>}
  </>}
 </div>;
}
