import { useEffect, useState } from "react";
import { desktopApi, type DiagnosticsResult, type StoreRecord } from "../lib/desktopApi";
import "./common.css";

interface Props{activeStore:StoreRecord|null;}
function bytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${(value/1024).toFixed(1)} KB`;return `${(value/1024/1024).toFixed(1)} MB`;}
export default function DiagnosticsPage({activeStore}:Props){const [info,setInfo]=useState<DiagnosticsResult|null>(null);const [connection,setConnection]=useState<Record<string,unknown>|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function refresh(){setBusy(true);setError("");try{setInfo(await desktopApi.diagnostics());}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 async function test(){if(!activeStore)return;setBusy(true);setError("");try{setConnection(await desktopApi.testStore(activeStore.id));}catch(reason){setError(String(reason));}finally{setBusy(false);}}
 async function report(){const data={generatedAt:new Date().toISOString(),diagnostics:info,activeStore:activeStore?{...activeStore,tokenPresent:activeStore.tokenPresent}:null,shopifyConnection:connection};await desktopApi.saveTextFile(`shopify-desktop-diagnostics-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(data,null,2));}
 useEffect(()=>{void refresh()},[]);
 return <div className="page-stack"><section className="page-hero"><div><span className="eyebrow">SYSTEM HEALTH</span><h2>Diagnostics and connection checks</h2><p>Review the local database, operating system, application paths, and the active Shopify connection.</p></div><aside><small>DATABASE</small><strong>{info?.databaseOk?"Healthy":"Checking"}</strong></aside></section>{error&&<div className="notice notice-error">! {error}</div>}<section className="stats-row"><div className="mini-stat"><span>App version</span><strong>{info?.appVersion||"—"}</strong></div><div className="mini-stat"><span>Stores</span><strong>{info?.storeCount??"—"}</strong></div><div className="mini-stat"><span>History</span><strong>{info?.historyCount??"—"}</strong></div><div className="mini-stat"><span>Database size</span><strong>{info?bytes(info.databaseSize):"—"}</strong></div></section><section className="grid-two"><article className="page-card"><header><div><h3>Local system</h3></div><button className="button-secondary" disabled={busy} onClick={()=>void refresh()}>Refresh</button></header><div className="page-card-body"><table className="data-table"><tbody><tr><th>Operating system</th><td>{info?.osName} {info?.osVersion}</td></tr><tr><th>Architecture</th><td>{info?.architecture}</td></tr><tr><th>App data</th><td className="monospace">{info?.appDataPath}</td></tr><tr><th>Database</th><td className="monospace">{info?.databasePath}</td></tr><tr><th>Quick check</th><td>{info?.databaseOk?"OK":"Failed"}</td></tr></tbody></table></div></article><article className="page-card"><header><div><h3>Shopify connection</h3><p>{activeStore?.domain||"No active store"}</p></div><button className="button-primary" disabled={busy||!activeStore} onClick={()=>void test()}>Test Connection</button></header><div className="page-card-body">{connection?<pre className="monospace" style={{whiteSpace:"pre-wrap",fontSize:10,maxHeight:320,overflow:"auto"}}>{JSON.stringify(connection,null,2)}</pre>:<div className="empty-state"><strong>No connection test yet</strong><p>Run a live Admin API query for the active store.</p></div>}</div></article></section><div className="form-actions"><button className="button-secondary" disabled={!info} onClick={()=>void report()}>Download Diagnostics Report</button></div></div>}
