import { useMemo, useState } from "react";
import { desktopApi, type HistoryRecord, type StoreRecord } from "../lib/desktopApi";
import { csvCell } from "../lib/fileSave";
import "./common.css";

interface Props { stores: StoreRecord[]; history: HistoryRecord[]; onHistoryChanged: () => void; }

function kindLabel(kind:string){return ({"product-import":"Product import","product-export":"Product export","collection-import":"Collection import","collection-export":"Collection export"} as Record<string,string>)[kind]||kind;}

export default function HistoryPage({stores,history,onHistoryChanged}:Props){
 const [search,setSearch]=useState("");const [kind,setKind]=useState("all");const [status,setStatus]=useState("all");const [storeId,setStoreId]=useState("all");const [error,setError]=useState("");
 const filtered=useMemo(()=>history.filter(item=>{const text=`${item.name} ${item.kind} ${item.status} ${item.detailsJson}`.toLowerCase();return (!search.trim()||text.includes(search.toLowerCase()))&&(kind==="all"||item.kind===kind)&&(status==="all"||item.status===status)&&(storeId==="all"||item.storeId===storeId);}),[history,search,kind,status,storeId]);
 async function remove(id:string){if(!window.confirm("Delete this local history record?"))return;try{await desktopApi.deleteHistory(id);onHistoryChanged();}catch(reason){setError(String(reason));}}
 async function clear(){if(!window.confirm("Delete all filtered local history records? Shopify data will not be changed."))return;try{for(const item of filtered)await desktopApi.deleteHistory(item.id);onHistoryChanged();}catch(reason){setError(String(reason));}}
 async function report(item:HistoryRecord){let details:unknown;try{details=JSON.parse(item.detailsJson);}catch{details=item.detailsJson;}const rows=Array.isArray(details)?details:[details];const columns=Array.from(new Set(rows.flatMap(row=>row&&typeof row==="object"?Object.keys(row as Record<string,unknown>):["value"])));const csv="\uFEFF"+[columns.map((column)=>csvCell(column)).join(","),...rows.map(row=>columns.map(column=>csvCell(row&&typeof row==="object"?(row as Record<string,unknown>)[column]:row)).join(","))].join("\r\n");await desktopApi.saveTextFile(`${item.kind}-${item.createdAt.slice(0,10)}-report.csv`,csv);}
 const completed=history.filter(x=>x.status==="COMPLETED").length, running=history.filter(x=>x.status==="RUNNING").length, failed=history.filter(x=>x.status==="FAILED").length;
 return <div className="page-stack">
  <section className="page-hero"><div><span className="eyebrow">LOCAL ACTIVITY</span><h2>Persistent import and export history</h2><p>Search operations, review warnings and errors, re-download reports, and clean local history without changing Shopify data.</p></div><aside><small>TOTAL RECORDS</small><strong>{history.length}</strong></aside></section>
  {error&&<div className="notice notice-error">! {error}</div>}
  <section className="stats-row"><div className="mini-stat"><span>Filtered</span><strong>{filtered.length}</strong></div><div className="mini-stat"><span>Completed</span><strong>{completed}</strong></div><div className="mini-stat"><span>Running</span><strong>{running}</strong></div><div className="mini-stat"><span>Failed</span><strong>{failed}</strong></div></section>
  <section className="page-card"><div className="toolbar"><div className="toolbar-group"><input placeholder="Search file, type, status, or error..." value={search} onChange={e=>setSearch(e.target.value)} /><select value={storeId} onChange={e=>setStoreId(e.target.value)}><option value="all">All stores</option>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All types</option><option value="product-import">Product import</option><option value="product-export">Product export</option><option value="collection-import">Collection import</option><option value="collection-export">Collection export</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="COMPLETED">Completed</option><option value="RUNNING">Running</option><option value="FAILED">Failed</option><option value="CANCELLED">Cancelled</option></select></div><button className="button-danger" disabled={filtered.length===0} onClick={()=>void clear()}>Delete Filtered</button></div>
   {filtered.length===0?<div className="empty-state"><strong>No activity found</strong><p>Change the filters or start a product or collection operation.</p></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Store</th><th>Type</th><th>Operation</th><th>Date</th><th>Progress</th><th>Results</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(item=>{const store=stores.find(s=>s.id===item.storeId);return <tr key={item.id}><td>{store?.name||"Deleted store"}</td><td><span className="status-pill">{kindLabel(item.kind)}</span></td><td><strong>{item.name}</strong><br/><small className="monospace">{item.filePath||"Local operation"}</small></td><td>{new Date(item.createdAt).toLocaleString()}</td><td><strong>{item.processed} / {item.total}</strong><br/><small>{item.total?Math.round(item.processed/item.total*100):0}%</small></td><td>{item.createdCount} created · {item.updatedCount} updated · {item.failedCount} failed</td><td><span className={`status-pill ${item.status==="COMPLETED"?"status-success":item.status==="FAILED"?"status-error":"status-running"}`}>{item.status}</span></td><td><div className="toolbar-group"><button className="button-text" onClick={()=>void report(item)}>Report</button><button className="button-text" onClick={()=>void remove(item.id)}>Delete</button></div></td></tr>})}</tbody></table></div>}
  </section>
 </div>;
}
