import * as XLSX from "xlsx";
export type AdminClient={graphql:(query:string,options?:{variables?:Record<string,unknown>})=>Promise<Response>};
export type DataRow=Record<string,unknown>;export type ExportFormat="csv"|"xlsx"|"json";
export async function graphqlData<T>(admin:AdminClient,query:string,variables:Record<string,unknown>={}):Promise<T>{const response=await admin.graphql(query,{variables});const payload=await response.json() as {data?:T;errors?:Array<{message:string}>};if(payload.errors?.length)throw new Error(payload.errors.map(x=>x.message).join(", "));if(!payload.data)throw new Error("Shopify did not return data for this request.");return payload.data;}
export function userErrorMessage(errors:Array<{field?:string[]|null;message:string}>|undefined){return(errors||[]).map(x=>`${x.field?.join(".")?`${x.field.join(".")}: `:""}${x.message}`).join(", ");}
export const optionalText=(v:unknown)=>String(v??"").trim();export function requiredText(v:unknown,l:string){const s=optionalText(v);if(!s)throw new Error(`${l} is required.`);return s;}export function numberValue(v:unknown,f=0){if(typeof v==="number"&&Number.isFinite(v))return v;const n=Number(String(v??"").trim().replace(/\s+/g,"").replace(",","."));return Number.isFinite(n)?n:f;}export const integerValue=(v:unknown,f=0)=>Math.trunc(numberValue(v,f));export function booleanValue(v:unknown,f=false){if(typeof v==="boolean")return v;const s=optionalText(v).toLowerCase();if(["true","1","yes","y","evet","ja"].includes(s))return true;if(["false","0","no","n","hayır","hayir","nein"].includes(s))return false;return f;}export function listValue(v:unknown){if(Array.isArray(v))return v.map(String).map(x=>x.trim()).filter(Boolean);return optionalText(v).split(/[,;|]/).map(x=>x.trim()).filter(Boolean);}export function slugify(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);}export function safeFileName(v:string){return v.replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g,"-").replace(/-+/g,"-").replace(/^-+|-+$/g,"")||"export";}
export function roundMoney(v:number,m:string){if(!Number.isFinite(v))return 0;if(m==="integer")return Math.round(v);if(m==="end-99")return Math.floor(v)+.99;if(m==="end-95")return Math.floor(v)+.95;if(m==="end-90")return Math.floor(v)+.9;return Math.round((v+Number.EPSILON)*100)/100;}export function adjustNumber(c:number,o:"increase"|"decrease"|"set",m:"percent"|"fixed",a:number){if(o==="set")return a;const d=m==="percent"?c*(a/100):a;return o==="increase"?c+d:c-d;}
export function firstValue(row:DataRow,names:string[]){const m=new Map(Object.entries(row).map(([k,v])=>[k.trim().toLowerCase().replace(/[^a-z0-9]+/g,""),v]));for(const n of names){const k=n.trim().toLowerCase().replace(/[^a-z0-9]+/g,"");if(m.has(k))return m.get(k);}return undefined;}
export function productFilterQuery(i:{query?:string;vendor?:string;productType?:string;tag?:string;collectionId?:string;status?:string}){const p=[optionalText(i.query)];if(i.vendor)p.push(`vendor:${JSON.stringify(i.vendor)}`);if(i.productType)p.push(`product_type:${JSON.stringify(i.productType)}`);if(i.tag)p.push(`tag:${JSON.stringify(i.tag)}`);if(i.collectionId)p.push(`collection_id:${i.collectionId.split("/").pop()}`);if(i.status)p.push(`status:${i.status}`);return p.filter(Boolean).join(" AND ");}
export const pause=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
function csvCell(v:unknown,d:string){const s=v==null?"":typeof v==="object"?JSON.stringify(v):String(v);return s.includes(d)||/["\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}export function rowsToCsv(rows:DataRow[],d=",",bom=true){if(!rows.length)return bom?"\ufeff":"";const cols=Array.from(new Set(rows.flatMap(Object.keys)));return`${bom?"\ufeff":""}${[cols.map(x=>csvCell(x,d)).join(d),...rows.map(r=>cols.map(c=>csvCell(r[c],d)).join(d))].join("\r\n")}`;}
export function rowsToFile(rows:DataRow[],format:ExportFormat):{base64?:string;text?:string;extension:string}{if(format==="json")return{text:JSON.stringify(rows,null,2),extension:"json"};if(format==="csv")return{text:rowsToCsv(rows),extension:"csv"};const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),"Data");return{base64:XLSX.write(wb,{type:"base64",bookType:"xlsx"}),extension:"xlsx"};}
export async function parseDataFile(file:File):Promise<DataRow[]>{const name=file.name.toLowerCase();if(name.endsWith(".json")){const v=JSON.parse(await file.text());if(Array.isArray(v))return v;if(v&&typeof v==="object")for(const k of["rows","items","customers","orders","articles","data"])if(Array.isArray(v[k]))return v[k];throw new Error("The JSON file must contain an array of records.");}const data=await file.arrayBuffer();const wb=XLSX.read(data,{type:"array",cellDates:true});const sn=wb.SheetNames[0];return sn?XLSX.utils.sheet_to_json<DataRow>(wb.Sheets[sn],{defval:"",raw:false}):[];}
export function bytesToBase64(bytes:Uint8Array){let out="";const size=0x8000;for(let i=0;i<bytes.length;i+=size)out+=String.fromCharCode(...bytes.subarray(i,i+size));return btoa(out);}export function base64ToBytes(value:string){const s=atob(value),out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out;}
