import {desktopApi} from "../desktopApi";import{graphqlData,pause,productFilterQuery,rowsToCsv,safeFileName,userErrorMessage,bytesToBase64,type AdminClient,type DataRow}from"./adminTools";
export type ZipEntry={name:string;base64Data:string};
const text64=(s:string)=>bytesToBase64(new TextEncoder().encode(s));
const extension=(url:string)=>{try{const m=new URL(url).pathname.match(/\.(jpe?g|png|webp|gif|avif|svg)$/i);return m?`.${m[1].toLowerCase().replace("jpeg","jpg")}`:".jpg"}catch{return".jpg"}};
const mime=(name:string)=>name.toLowerCase().endsWith(".png")?"image/png":name.toLowerCase().endsWith(".webp")?"image/webp":name.toLowerCase().endsWith(".gif")?"image/gif":name.toLowerCase().endsWith(".avif")?"image/avif":"image/jpeg";
export async function downloadProductImagesDesktop(admin:AdminClient,filters:{query:string;vendor:string;productType:string;tag:string;collectionId:string;limit:number}){const query=productFilterQuery(filters),entries:ZipEntry[]=[],manifest:DataRow[]=[];let cursor:string|null=null,count=0,products=0;const limit=Math.max(1,Math.min(filters.limit||2000,10000));while(count<limit){const data=await graphqlData<{products:{nodes:Array<{id:string;title:string;handle:string;variants:{nodes:Array<{id:string;sku:string|null}>};media:{nodes:Array<{id:string;alt:string|null;image:{url:string;width:number;height:number}|null}>}}>;pageInfo:{hasNextPage:boolean;endCursor:string|null}}}>(admin,`#graphql
query ProductImageExport($first:Int!,$after:String,$query:String){products(first:$first,after:$after,query:$query,sortKey:TITLE){nodes{id title handle variants(first:250){nodes{id sku}} media(first:250){nodes{... on MediaImage{id alt image{url width height}}}}}pageInfo{hasNextPage endCursor}}}`,{first:40,after:cursor,query:query||null});for(const product of data.products.nodes){const sku=product.variants.nodes.find(v=>v.sku?.trim())?.sku?.trim()||product.handle;if(!sku||!product.media.nodes.length)continue;products++;let pos=0;for(const media of product.media.nodes){if(!media.image?.url||count>=limit)continue;pos++;const name=`${safeFileName(sku)}_${String(pos).padStart(2,"0")}${extension(media.image.url)}`;try{entries.push({name:`images/${name}`,base64Data:await desktopApi.httpGetBinary(media.image.url)});manifest.push({SKU:sku,"File Name":name,"Product ID":product.id,"Product Title":product.title,"Media ID":media.id,Position:pos,"Original URL":media.image.url,"Alt Text":media.alt||"",Width:media.image.width,Height:media.image.height});count++;}catch(e){manifest.push({SKU:sku,"File Name":name,"Original URL":media.image.url,Error:String(e)})}await pause(20)}}if(!data.products.pageInfo.hasNextPage||!data.products.pageInfo.endCursor)break;cursor=data.products.pageInfo.endCursor}entries.unshift({name:"manifest.csv",base64Data:text64(rowsToCsv(manifest))},{name:"README.txt",base64Data:text64("Images are named SKU_01, SKU_02, and so on. Upload this ZIP in the same module.\r\n")});return{entries,count,products};}
async function findBySku(admin:AdminClient,sku:string){const d=await graphqlData<{productVariants:{nodes:Array<{id:string;sku:string|null;product:{id:string;title:string;media:{nodes:Array<{id:string}>}}}>}}>(admin,`#graphql
query ProductImageSku($query:String!){productVariants(first:5,query:$query){nodes{id sku product{id title media(first:250){nodes{id}}}}}}`,{query:`sku:${JSON.stringify(sku)}`});const v=d.productVariants.nodes.find(x=>x.sku===sku)||d.productVariants.nodes[0];return v?{variantId:v.id,productId:v.product.id,title:v.product.title,mediaIds:v.product.media.nodes.map(x=>x.id)}:null;}
async function stage(admin:AdminClient,name:string,base64Data:string){const d=await graphqlData<{stagedUploadsCreate:{stagedTargets:Array<{url:string;resourceUrl:string;parameters:Array<{name:string;value:string}>}>;userErrors:Array<{field?:string[];message:string}>}}>(admin,`#graphql
mutation ProductImageStage($input:[StagedUploadInput!]!){stagedUploadsCreate(input:$input){stagedTargets{url resourceUrl parameters{name value}} userErrors{field message}}}`,{input:[{filename:name,mimeType:mime(name),resource:"PRODUCT_IMAGE",httpMethod:"POST"}]});const err=userErrorMessage(d.stagedUploadsCreate.userErrors);if(err)throw new Error(err);const target=d.stagedUploadsCreate.stagedTargets[0];if(!target)throw new Error("Shopify did not return a staged upload target.");await desktopApi.httpPostMultipart(target.url,target.parameters,name,mime(name),base64Data);return target.resourceUrl;}
export async function uploadProductImagesDesktop(admin:AdminClient,entries:ZipEntry[],mode:"append"|"replace"){const images=entries.filter(x=>/\.(jpe?g|png|webp|gif|avif)$/i.test(x.name)&&!x.name.startsWith("__MACOSX/")),groups=new Map<string,ZipEntry[]>();for(const item of images){const file=item.name.split(/[\\/]/).pop()||item.name;const base=file.replace(/\.[^.]+$/g,"");const m=base.match(/^(.+?)(?:[_-](\d{1,4}))?(?:[_-]\d+)?$/);const sku=(m?.[1]||base).trim();groups.set(sku,[...(groups.get(sku)||[]),{...item,name:file}]);}const result={total:images.length,uploaded:0,skipped:0,failed:0,errors:[] as string[]};for(const[sku,list]of groups){const target=await findBySku(admin,sku);if(!target){result.skipped+=list.length;result.errors.push(`${sku}: SKU was not found.`);continue}try{if(mode==="replace"&&target.mediaIds.length){const d=await graphqlData<{productDeleteMedia:{mediaUserErrors:Array<{field?:string[];message:string}>}}>(admin,`#graphql
mutation DeleteMedia($productId:ID!,$mediaIds:[ID!]!){productDeleteMedia(productId:$productId,mediaIds:$mediaIds){mediaUserErrors{field message}}}`,{productId:target.productId,mediaIds:target.mediaIds});const e=userErrorMessage(d.productDeleteMedia.mediaUserErrors);if(e)throw new Error(e)}for(const image of list.sort((a,b)=>a.name.localeCompare(b.name))){try{const resourceUrl=await stage(admin,image.name,image.base64Data);const d=await graphqlData<{productUpdate:{userErrors:Array<{field?:string[];message:string}>}}>(admin,`#graphql
mutation AttachMedia($product:ProductUpdateInput!,$media:[CreateMediaInput!]){productUpdate(product:$product,media:$media){userErrors{field message}}}`,{product:{id:target.productId},media:[{originalSource:resourceUrl,mediaContentType:"IMAGE",alt:`${target.title} - ${sku}`}]});const e=userErrorMessage(d.productUpdate.userErrors);if(e)throw new Error(e);await graphqlData(admin,`#graphql
mutation VariantMedia($productId:ID!,$variants:[ProductVariantsBulkInput!]!){productVariantsBulkUpdate(productId:$productId,variants:$variants,allowPartialUpdates:true){userErrors{field message}}}`,{productId:target.productId,variants:[{id:target.variantId,mediaSrc:[resourceUrl]}]});result.uploaded++;}catch(e){result.failed++;result.errors.push(`${sku}/${image.name}: ${String(e)}`)}await pause(160)}}catch(e){result.failed+=list.length;result.errors.push(`${sku}: ${String(e)}`)}}return result;}
export async function downloadStoreMediaDesktop(admin:AdminClient,options:{includeFiles:boolean;includeCollections:boolean;includeArticles:boolean;fileQuery:string;limit:number}){type S={group:string;id:string;title:string;url:string;alt:string};const sources:S[]=[];const limit=Math.min(Math.max(options.limit||2000,1),10000);if(options.includeFiles){let cursor:string|null=null;while(sources.filter(x=>x.group==="files").length<limit){const d=await graphqlData<{files:{nodes:Array<{__typename:string;id:string;alt:string|null;image?:{url:string}|null;url?:string|null}>;pageInfo:{hasNextPage:boolean;endCursor:string|null}}}>(admin,`#graphql
query Files($first:Int!,$after:String,$query:String){files(first:$first,after:$after,query:$query){nodes{__typename id alt ... on MediaImage{image{url}} ... on GenericFile{url}}pageInfo{hasNextPage endCursor}}}`,{first:100,after:cursor,query:options.fileQuery||"media_type:IMAGE"});for(const x of d.files.nodes){const url=x.image?.url||x.url||"";if(url)sources.push({group:"files",id:x.id,title:x.alt||"store-file",url,alt:x.alt||""})}if(!d.files.pageInfo.hasNextPage||!d.files.pageInfo.endCursor)break;cursor=d.files.pageInfo.endCursor}}
if(options.includeCollections){const d=await graphqlData<{collections:{nodes:Array<{id:string;title:string;handle:string;image:{url:string;altText:string|null}|null}>}}>(admin,`#graphql
query CollectionMedia($first:Int!){collections(first:$first){nodes{id title handle image{url altText}}}}`,{first:Math.min(limit,250)});for(const x of d.collections.nodes)if(x.image?.url)sources.push({group:"collections",id:x.id,title:x.handle||x.title,url:x.image.url,alt:x.image.altText||""})}
if(options.includeArticles){const d=await graphqlData<{articles:{nodes:Array<{id:string;title:string;handle:string;blog:{handle:string};image:{url:string;altText:string|null}|null}>}}>(admin,`#graphql
query ArticleMedia($first:Int!){articles(first:$first,sortKey:UPDATED_AT,reverse:true){nodes{id title handle blog{handle} image{url altText}}}}`,{first:Math.min(limit,250)});for(const x of d.articles.nodes)if(x.image?.url)sources.push({group:`blogs/${x.blog.handle}`,id:x.id,title:x.handle||x.title,url:x.image.url,alt:x.image.altText||""})}
const unique=[...new Map(sources.map(x=>[x.url,x])).values()],entries:ZipEntry[]=[],manifest:DataRow[]=[];for(const x of unique){const name=`${x.group.split("/").map(safeFileName).join("/")}/${safeFileName(x.title)}${extension(x.url)}`;try{entries.push({name,base64Data:await desktopApi.httpGetBinary(x.url)});manifest.push({Group:x.group,"File Name":name,"Resource ID":x.id,Title:x.title,URL:x.url,"Alt Text":x.alt})}catch(e){manifest.push({Group:x.group,"Resource ID":x.id,URL:x.url,Error:String(e)})}}entries.unshift({name:"manifest.csv",base64Data:text64(rowsToCsv(manifest))},{name:"README.txt",base64Data:text64("Non-product images from Shopify Files, collection covers, and blog articles.\r\n")});return{entries,count:unique.length};}
