import { useCallback, useEffect, useMemo, useState } from "react";
import { openUrl } from "@tauri-apps/plugin-opener";
import "./App.css";
import "./pages/common.css";
import ProductImportPage from "./pages/ProductImportPage";
import ProductExportPage from "./pages/ProductExportPage";
import CollectionImportPage from "./pages/CollectionImportPage";
import CollectionExportPage from "./pages/CollectionExportPage";
import StoresPage from "./pages/StoresPage";
import SettingsPage from "./pages/SettingsPage";
import HistoryPage from "./pages/HistoryPage";
import TemplatesPage from "./pages/TemplatesPage";
import BackupPage from "./pages/BackupPage";
import DiagnosticsPage from "./pages/DiagnosticsPage";
import PriceManagerPage from "./pages/PriceManagerPage";
import InventoryManagerPage from "./pages/InventoryManagerPage";
import CustomerTransferPage from "./pages/CustomerTransferPage";
import OrderTransferPage from "./pages/OrderTransferPage";
import BlogTransferPage from "./pages/BlogTransferPage";
import DiscountManagerPage from "./pages/DiscountManagerPage";
import ProductImagesPage from "./pages/ProductImagesPage";
import StoreMediaPage from "./pages/StoreMediaPage";
import { DEFAULT_SETTINGS, normalizeSettings, type AppSettings } from "./lib/appSettings";
import { desktopApi, type HistoryRecord, type StoreRecord } from "./lib/desktopApi";

type PageId="dashboard"|"stores"|"product-import"|"product-export"|"price-manager"|"inventory-manager"|"customer-transfer"|"order-transfer"|"collection-import"|"collection-export"|"blog-transfer"|"discount-manager"|"product-images"|"store-media"|"history"|"templates"|"backup"|"diagnostics"|"settings";
const menuItems:Array<{id:PageId;label:string;icon:string}>=[
 {id:"dashboard",label:"Home",icon:"⌂"},{id:"stores",label:"Stores",icon:"□"},{id:"product-import",label:"Product Import",icon:"↑"},{id:"product-export",label:"Product Export",icon:"↓"},{id:"price-manager",label:"Price Manager",icon:"€"},{id:"inventory-manager",label:"Inventory Manager",icon:"#"},{id:"customer-transfer",label:"Customer Transfer",icon:"C"},{id:"order-transfer",label:"Order Transfer",icon:"O"},{id:"collection-import",label:"Collection Import",icon:"▦"},{id:"collection-export",label:"Collection Export",icon:"▤"},{id:"blog-transfer",label:"Blog Transfer",icon:"B"},{id:"discount-manager",label:"Discount Manager",icon:"%"},{id:"product-images",label:"SKU Product Images",icon:"I"},{id:"store-media",label:"Store Media Export",icon:"M"},{id:"history",label:"Activity History",icon:"◷"},{id:"templates",label:"File Templates",icon:"▧"},{id:"backup",label:"Backup & Restore",icon:"◫"},{id:"diagnostics",label:"Diagnostics",icon:"!"},{id:"settings",label:"Settings",icon:"⚙"},
];
const pageTitles=Object.fromEntries(menuItems.map(x=>[x.id,x.label])) as Record<PageId,string>;

interface DashboardStats{products:number;collections:number;locations:number;currency:string;storeName:string;}

function App(){
 const [activePage,setActivePage]=useState<PageId>("dashboard");const [darkMode,setDarkMode]=useState(false);const [stores,setStores]=useState<StoreRecord[]>([]);const [history,setHistory]=useState<HistoryRecord[]>([]);const [settings,setSettings]=useState<AppSettings>(DEFAULT_SETTINGS);const [stats,setStats]=useState<DashboardStats|null>(null);const [loading,setLoading]=useState(true);const [globalError,setGlobalError]=useState("");
 const activeStore=useMemo(()=>stores.find(s=>s.isActive)||stores[0]||null,[stores]);
 const loadStores=useCallback(async()=>{const result=await desktopApi.listStores();setStores(result);return result;},[]);
 const loadHistory=useCallback(async()=>{setHistory(await desktopApi.listHistory(undefined,500));},[]);
 const loadSettings=useCallback(async(store:StoreRecord|null)=>{if(!store){setSettings(DEFAULT_SETTINGS);return;}setSettings(normalizeSettings(await desktopApi.getSettings(store.id)));},[]);
 const loadStats=useCallback(async(store:StoreRecord|null)=>{if(!store||!store.tokenPresent){setStats(null);return;}try{const result=await desktopApi.testStore(store.id);const data=result.data as {shop?:{name?:string;currencyCode?:string};locations?:{nodes?:Array<{isActive?:boolean}>};productsCount?:{count?:number};collectionsCount?:{count?:number}}|undefined;setStats({products:Number(data?.productsCount?.count||0),collections:Number(data?.collectionsCount?.count||0),locations:(data?.locations?.nodes||[]).filter(x=>x.isActive).length,currency:data?.shop?.currencyCode||"—",storeName:data?.shop?.name||store.name});}catch{setStats(null);}},[]);
 const refreshAll=useCallback(async()=>{setLoading(true);setGlobalError("");try{const loaded=await loadStores();const active=loaded.find(s=>s.isActive)||loaded[0]||null;await Promise.all([loadHistory(),loadSettings(active),loadStats(active)]);}catch(reason){setGlobalError(String(reason));}finally{setLoading(false);}},[loadStores,loadHistory,loadSettings,loadStats]);
 useEffect(()=>{void refreshAll()},[refreshAll]);
 async function switchStore(id:string){try{await desktopApi.setActiveStore(id);const loaded=await loadStores();const active=loaded.find(s=>s.isActive)||null;await Promise.all([loadSettings(active),loadStats(active)]);}catch(reason){setGlobalError(String(reason));}}
 function renderPage(){switch(activePage){case"dashboard":return <Dashboard activeStore={activeStore} stores={stores} stats={stats} history={history} onNavigate={setActivePage}/>;case"stores":return <StoresPage stores={stores} onStoresChanged={refreshAll}/>;case"product-import":return <ProductImportPage activeStore={activeStore} settings={settings} onHistoryChanged={loadHistory}/>;case"product-export":return <ProductExportPage activeStore={activeStore} settings={settings} onHistoryChanged={loadHistory}/>;case"price-manager":return <PriceManagerPage activeStore={activeStore}/>;case"inventory-manager":return <InventoryManagerPage activeStore={activeStore}/>;case"customer-transfer":return <CustomerTransferPage activeStore={activeStore}/>;case"order-transfer":return <OrderTransferPage activeStore={activeStore}/>;case"collection-import":return <CollectionImportPage activeStore={activeStore} settings={settings} onHistoryChanged={loadHistory}/>;case"collection-export":return <CollectionExportPage activeStore={activeStore} settings={settings} onHistoryChanged={loadHistory}/>;case"blog-transfer":return <BlogTransferPage activeStore={activeStore}/>;case"discount-manager":return <DiscountManagerPage activeStore={activeStore}/>;case"product-images":return <ProductImagesPage activeStore={activeStore}/>;case"store-media":return <StoreMediaPage activeStore={activeStore}/>;case"history":return <HistoryPage stores={stores} history={history} onHistoryChanged={loadHistory}/>;case"templates":return <TemplatesPage settings={settings}/>;case"backup":return <BackupPage onRestored={refreshAll}/>;case"diagnostics":return <DiagnosticsPage activeStore={activeStore}/>;case"settings":return <SettingsPage activeStore={activeStore} settings={settings} onSettingsChanged={setSettings}/>;}}
 return <div className={darkMode?"app dark":"app"}>
  <aside className="sidebar"><div className="brand"><div className="brand-logo">SP</div><div className="brand-text"><strong>Shopify Product/</strong><span>Collection Upload</span></div></div><nav className="sidebar-menu"><p className="menu-title">APPLICATION</p>{menuItems.map(item=><button key={item.id} className={activePage===item.id?"menu-item menu-item-active":"menu-item"} onClick={()=>setActivePage(item.id)}><span className="menu-icon">{item.icon}</span><span>{item.label}</span></button>)}</nav><div className="sidebar-footer"><div className="connection-status"><span className="status-dot" style={{background:activeStore?.tokenPresent?"#1fbf8f":"#f2a93b"}}/><div><strong>{activeStore?.name||"Local Mode"}</strong><small>{activeStore?.tokenPresent?activeStore.domain:"No active Shopify connection"}</small></div></div><div className="version">Version 2.0.0</div></div></aside>
  <main className="main"><header className="topbar"><div><p className="breadcrumb">Shopify Product/Collection Upload</p><h1>{pageTitles[activePage]}</h1></div><div className="topbar-actions">{stores.length>0&&<select className="store-selector" value={activeStore?.id||""} onChange={e=>void switchStore(e.target.value)}>{stores.map(s=><option value={s.id} key={s.id}>{s.name} · {s.domain}</option>)}</select>}<button className="theme-button" onClick={()=>setDarkMode(x=>!x)} title="Change theme">{darkMode?"☀":"☾"}</button><div className="user-box"><div className="user-avatar">{(activeStore?.name||"HB").slice(0,2).toUpperCase()}</div><div><strong>{activeStore?.name||"Hausone GmbH"}</strong><small>{activeStore?.tokenPresent?"Connected store":"Local desktop"}</small></div></div></div></header>
  <section className="content">{globalError&&<div className="notice notice-error" style={{marginBottom:16}}>! {globalError}</div>}{loading?<div className="empty-state"><strong>Loading local workspace...</strong></div>:renderPage()}</section></main>
 </div>;
}

function Dashboard({activeStore,stores,stats,history,onNavigate}:{activeStore:StoreRecord|null;stores:StoreRecord[];stats:DashboardStats|null;history:HistoryRecord[];onNavigate:(id:PageId)=>void}){
 const activeHistory=activeStore?history.filter(x=>x.storeId===activeStore.id):history;const failed=activeHistory.filter(x=>x.status==="FAILED").length;const imports=activeHistory.filter(x=>x.kind.includes("import")&&x.status==="COMPLETED").reduce((sum,x)=>sum+x.processed,0);const exports=activeHistory.filter(x=>x.kind.includes("export")&&x.status==="COMPLETED").length;
 return <><section className="welcome-card"><div><span className="welcome-label">{activeStore?"CONNECTED STORE":"LOCAL DESKTOP"}</span><h2>{activeStore?activeStore.name:"Manage products and collections from one place."}</h2><p>{activeStore?"Use the active Shopify store for product, price, inventory, customer, order, content, image, discount, and collection operations.":"Add one or more Shopify stores. Each access token is stored securely in the operating system credential vault."}</p><div className="welcome-actions"><button className="primary-button" onClick={()=>onNavigate(activeStore?"product-import":"stores")}>{activeStore?"Start Product Import":"Add First Store"}</button>{activeStore&&<button className="secondary-button" onClick={()=>void openUrl(`https://${activeStore.domain}`)}>Open Store</button>}</div></div><div className="welcome-visual"><div className="visual-card visual-card-one"><span>CSV</span></div><div className="visual-card visual-card-two"><span>XLSX</span></div><div className="visual-card visual-card-three"><span>JSON</span></div></div></section>
 <section className="stats-grid"><StatCard title="Connected stores" value={String(stores.length)} description={activeStore?.domain||"No active store"} icon="□"/><StatCard title="Products" value={String(stats?.products??0)} description={`${imports} imported locally`} icon="↑"/><StatCard title="Collections" value={String(stats?.collections??0)} description={`${exports} export operations`} icon="▦"/><StatCard title="Failed operations" value={String(failed)} description={`${stats?.locations??0} active locations`} icon="!"/></section>
 <section className="dashboard-grid"><div className="panel quick-actions"><div className="panel-header"><div><h3>Quick Actions</h3><p>Open the most frequently used desktop tools.</p></div></div><div className="action-grid"><ActionCard title="Product Import" description="Import CSV, Excel, or JSON products." icon="↑" onClick={()=>onNavigate("product-import")}/><ActionCard title="Product Export" description="Export complete store product data." icon="↓" onClick={()=>onNavigate("product-export")}/><ActionCard title="Collection Import" description="Import hybrid collection sources." icon="▦" onClick={()=>onNavigate("collection-import")}/><ActionCard title="File Templates" description="Download product and collection templates." icon="▧" onClick={()=>onNavigate("templates")}/></div></div><div className="panel recent-panel"><div className="panel-header"><div><h3>Recent Activity</h3><p>Latest local import and export operations.</p></div><button className="text-button" onClick={()=>onNavigate("history")}>View All</button></div>{activeHistory.length===0?<div className="empty-recent"><div className="empty-recent-icon">◷</div><strong>No activity yet</strong><span>Your first local operation will appear here.</span></div>:<div>{activeHistory.slice(0,5).map(item=><div key={item.id} style={{padding:"12px 18px",borderBottom:"1px solid var(--border)"}}><strong style={{fontSize:11}}>{item.name}</strong><div style={{display:"flex",justifyContent:"space-between",marginTop:4,fontSize:10,color:"var(--text-secondary)"}}><span>{item.kind}</span><span>{item.status}</span></div></div>)}</div>}</div></section></>;
}
function StatCard({title,value,description,icon}:{title:string;value:string;description:string;icon:string}){return <article className="stat-card"><div className="stat-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{description}</small></div></article>}
function ActionCard({title,description,icon,onClick}:{title:string;description:string;icon:string;onClick:()=>void}){return <button className="action-card" onClick={onClick}><span className="action-icon">{icon}</span><div><strong>{title}</strong><small>{description}</small></div><span className="action-arrow">›</span></button>}
export default App;
